<?php
/**
 * StudiosApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.10
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * StudiosApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StudiosApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getStudio' => [
            'application/json',
        ],
        'getStudios' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getStudio
     *
     * Gets a studio by name.
     *
     * @param  string $name Studio name. (required)
     * @param  string $user_id Optional. Filter by user id, and attach user data. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStudio'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\BaseItemDto
     */
    public function getStudio($name, $user_id = null, string $contentType = self::contentTypes['getStudio'][0])
    {
        list($response) = $this->getStudioWithHttpInfo($name, $user_id, $contentType);
        return $response;
    }

    /**
     * Operation getStudioWithHttpInfo
     *
     * Gets a studio by name.
     *
     * @param  string $name Studio name. (required)
     * @param  string $user_id Optional. Filter by user id, and attach user data. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStudio'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\BaseItemDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function getStudioWithHttpInfo($name, $user_id = null, string $contentType = self::contentTypes['getStudio'][0])
    {
        $request = $this->getStudioRequest($name, $user_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\BaseItemDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\BaseItemDto' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\BaseItemDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\BaseItemDto';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BaseItemDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getStudioAsync
     *
     * Gets a studio by name.
     *
     * @param  string $name Studio name. (required)
     * @param  string $user_id Optional. Filter by user id, and attach user data. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStudio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStudioAsync($name, $user_id = null, string $contentType = self::contentTypes['getStudio'][0])
    {
        return $this->getStudioAsyncWithHttpInfo($name, $user_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getStudioAsyncWithHttpInfo
     *
     * Gets a studio by name.
     *
     * @param  string $name Studio name. (required)
     * @param  string $user_id Optional. Filter by user id, and attach user data. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStudio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStudioAsyncWithHttpInfo($name, $user_id = null, string $contentType = self::contentTypes['getStudio'][0])
    {
        $returnType = '\OpenAPI\Client\Model\BaseItemDto';
        $request = $this->getStudioRequest($name, $user_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getStudio'
     *
     * @param  string $name Studio name. (required)
     * @param  string $user_id Optional. Filter by user id, and attach user data. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStudio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getStudioRequest($name, $user_id = null, string $contentType = self::contentTypes['getStudio'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling getStudio'
            );
        }



        $resourcePath = '/Studios/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $user_id,
            'userId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/json; profile="CamelCase"', 'application/json; profile="PascalCase"', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getStudios
     *
     * Gets all studios from a given item, folder, or the entire library.
     *
     * @param  int $start_index Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)
     * @param  int $limit Optional. The maximum number of records to return. (optional)
     * @param  string $search_term Optional. Search term. (optional)
     * @param  string $parent_id Specify this to localize the search to a specific item or folder. Omit to use the root. (optional)
     * @param  \OpenAPI\Client\Model\ItemFields[] $fields Optional. Specify additional fields of information to return in the output. (optional)
     * @param  \OpenAPI\Client\Model\BaseItemKind[] $exclude_item_types Optional. If specified, results will be filtered out based on item type. This allows multiple, comma delimited. (optional)
     * @param  \OpenAPI\Client\Model\BaseItemKind[] $include_item_types Optional. If specified, results will be filtered based on item type. This allows multiple, comma delimited. (optional)
     * @param  bool $is_favorite Optional filter by items that are marked as favorite, or not. (optional)
     * @param  bool $enable_user_data Optional, include user data. (optional)
     * @param  int $image_type_limit Optional, the max number of images to return, per image type. (optional)
     * @param  \OpenAPI\Client\Model\ImageType[] $enable_image_types Optional. The image types to include in the output. (optional)
     * @param  string $user_id User id. (optional)
     * @param  string $name_starts_with_or_greater Optional filter by items whose name is sorted equally or greater than a given input string. (optional)
     * @param  string $name_starts_with Optional filter by items whose name is sorted equally than a given input string. (optional)
     * @param  string $name_less_than Optional filter by items whose name is equally or lesser than a given input string. (optional)
     * @param  bool $enable_images Optional, include image information in output. (optional, default to true)
     * @param  bool $enable_total_record_count Total record count. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStudios'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\BaseItemDtoQueryResult
     */
    public function getStudios($start_index = null, $limit = null, $search_term = null, $parent_id = null, $fields = null, $exclude_item_types = null, $include_item_types = null, $is_favorite = null, $enable_user_data = null, $image_type_limit = null, $enable_image_types = null, $user_id = null, $name_starts_with_or_greater = null, $name_starts_with = null, $name_less_than = null, $enable_images = true, $enable_total_record_count = true, string $contentType = self::contentTypes['getStudios'][0])
    {
        list($response) = $this->getStudiosWithHttpInfo($start_index, $limit, $search_term, $parent_id, $fields, $exclude_item_types, $include_item_types, $is_favorite, $enable_user_data, $image_type_limit, $enable_image_types, $user_id, $name_starts_with_or_greater, $name_starts_with, $name_less_than, $enable_images, $enable_total_record_count, $contentType);
        return $response;
    }

    /**
     * Operation getStudiosWithHttpInfo
     *
     * Gets all studios from a given item, folder, or the entire library.
     *
     * @param  int $start_index Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)
     * @param  int $limit Optional. The maximum number of records to return. (optional)
     * @param  string $search_term Optional. Search term. (optional)
     * @param  string $parent_id Specify this to localize the search to a specific item or folder. Omit to use the root. (optional)
     * @param  \OpenAPI\Client\Model\ItemFields[] $fields Optional. Specify additional fields of information to return in the output. (optional)
     * @param  \OpenAPI\Client\Model\BaseItemKind[] $exclude_item_types Optional. If specified, results will be filtered out based on item type. This allows multiple, comma delimited. (optional)
     * @param  \OpenAPI\Client\Model\BaseItemKind[] $include_item_types Optional. If specified, results will be filtered based on item type. This allows multiple, comma delimited. (optional)
     * @param  bool $is_favorite Optional filter by items that are marked as favorite, or not. (optional)
     * @param  bool $enable_user_data Optional, include user data. (optional)
     * @param  int $image_type_limit Optional, the max number of images to return, per image type. (optional)
     * @param  \OpenAPI\Client\Model\ImageType[] $enable_image_types Optional. The image types to include in the output. (optional)
     * @param  string $user_id User id. (optional)
     * @param  string $name_starts_with_or_greater Optional filter by items whose name is sorted equally or greater than a given input string. (optional)
     * @param  string $name_starts_with Optional filter by items whose name is sorted equally than a given input string. (optional)
     * @param  string $name_less_than Optional filter by items whose name is equally or lesser than a given input string. (optional)
     * @param  bool $enable_images Optional, include image information in output. (optional, default to true)
     * @param  bool $enable_total_record_count Total record count. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStudios'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\BaseItemDtoQueryResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function getStudiosWithHttpInfo($start_index = null, $limit = null, $search_term = null, $parent_id = null, $fields = null, $exclude_item_types = null, $include_item_types = null, $is_favorite = null, $enable_user_data = null, $image_type_limit = null, $enable_image_types = null, $user_id = null, $name_starts_with_or_greater = null, $name_starts_with = null, $name_less_than = null, $enable_images = true, $enable_total_record_count = true, string $contentType = self::contentTypes['getStudios'][0])
    {
        $request = $this->getStudiosRequest($start_index, $limit, $search_term, $parent_id, $fields, $exclude_item_types, $include_item_types, $is_favorite, $enable_user_data, $image_type_limit, $enable_image_types, $user_id, $name_starts_with_or_greater, $name_starts_with, $name_less_than, $enable_images, $enable_total_record_count, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\BaseItemDtoQueryResult' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\BaseItemDtoQueryResult' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\BaseItemDtoQueryResult', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\BaseItemDtoQueryResult';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BaseItemDtoQueryResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getStudiosAsync
     *
     * Gets all studios from a given item, folder, or the entire library.
     *
     * @param  int $start_index Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)
     * @param  int $limit Optional. The maximum number of records to return. (optional)
     * @param  string $search_term Optional. Search term. (optional)
     * @param  string $parent_id Specify this to localize the search to a specific item or folder. Omit to use the root. (optional)
     * @param  \OpenAPI\Client\Model\ItemFields[] $fields Optional. Specify additional fields of information to return in the output. (optional)
     * @param  \OpenAPI\Client\Model\BaseItemKind[] $exclude_item_types Optional. If specified, results will be filtered out based on item type. This allows multiple, comma delimited. (optional)
     * @param  \OpenAPI\Client\Model\BaseItemKind[] $include_item_types Optional. If specified, results will be filtered based on item type. This allows multiple, comma delimited. (optional)
     * @param  bool $is_favorite Optional filter by items that are marked as favorite, or not. (optional)
     * @param  bool $enable_user_data Optional, include user data. (optional)
     * @param  int $image_type_limit Optional, the max number of images to return, per image type. (optional)
     * @param  \OpenAPI\Client\Model\ImageType[] $enable_image_types Optional. The image types to include in the output. (optional)
     * @param  string $user_id User id. (optional)
     * @param  string $name_starts_with_or_greater Optional filter by items whose name is sorted equally or greater than a given input string. (optional)
     * @param  string $name_starts_with Optional filter by items whose name is sorted equally than a given input string. (optional)
     * @param  string $name_less_than Optional filter by items whose name is equally or lesser than a given input string. (optional)
     * @param  bool $enable_images Optional, include image information in output. (optional, default to true)
     * @param  bool $enable_total_record_count Total record count. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStudios'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStudiosAsync($start_index = null, $limit = null, $search_term = null, $parent_id = null, $fields = null, $exclude_item_types = null, $include_item_types = null, $is_favorite = null, $enable_user_data = null, $image_type_limit = null, $enable_image_types = null, $user_id = null, $name_starts_with_or_greater = null, $name_starts_with = null, $name_less_than = null, $enable_images = true, $enable_total_record_count = true, string $contentType = self::contentTypes['getStudios'][0])
    {
        return $this->getStudiosAsyncWithHttpInfo($start_index, $limit, $search_term, $parent_id, $fields, $exclude_item_types, $include_item_types, $is_favorite, $enable_user_data, $image_type_limit, $enable_image_types, $user_id, $name_starts_with_or_greater, $name_starts_with, $name_less_than, $enable_images, $enable_total_record_count, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getStudiosAsyncWithHttpInfo
     *
     * Gets all studios from a given item, folder, or the entire library.
     *
     * @param  int $start_index Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)
     * @param  int $limit Optional. The maximum number of records to return. (optional)
     * @param  string $search_term Optional. Search term. (optional)
     * @param  string $parent_id Specify this to localize the search to a specific item or folder. Omit to use the root. (optional)
     * @param  \OpenAPI\Client\Model\ItemFields[] $fields Optional. Specify additional fields of information to return in the output. (optional)
     * @param  \OpenAPI\Client\Model\BaseItemKind[] $exclude_item_types Optional. If specified, results will be filtered out based on item type. This allows multiple, comma delimited. (optional)
     * @param  \OpenAPI\Client\Model\BaseItemKind[] $include_item_types Optional. If specified, results will be filtered based on item type. This allows multiple, comma delimited. (optional)
     * @param  bool $is_favorite Optional filter by items that are marked as favorite, or not. (optional)
     * @param  bool $enable_user_data Optional, include user data. (optional)
     * @param  int $image_type_limit Optional, the max number of images to return, per image type. (optional)
     * @param  \OpenAPI\Client\Model\ImageType[] $enable_image_types Optional. The image types to include in the output. (optional)
     * @param  string $user_id User id. (optional)
     * @param  string $name_starts_with_or_greater Optional filter by items whose name is sorted equally or greater than a given input string. (optional)
     * @param  string $name_starts_with Optional filter by items whose name is sorted equally than a given input string. (optional)
     * @param  string $name_less_than Optional filter by items whose name is equally or lesser than a given input string. (optional)
     * @param  bool $enable_images Optional, include image information in output. (optional, default to true)
     * @param  bool $enable_total_record_count Total record count. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStudios'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStudiosAsyncWithHttpInfo($start_index = null, $limit = null, $search_term = null, $parent_id = null, $fields = null, $exclude_item_types = null, $include_item_types = null, $is_favorite = null, $enable_user_data = null, $image_type_limit = null, $enable_image_types = null, $user_id = null, $name_starts_with_or_greater = null, $name_starts_with = null, $name_less_than = null, $enable_images = true, $enable_total_record_count = true, string $contentType = self::contentTypes['getStudios'][0])
    {
        $returnType = '\OpenAPI\Client\Model\BaseItemDtoQueryResult';
        $request = $this->getStudiosRequest($start_index, $limit, $search_term, $parent_id, $fields, $exclude_item_types, $include_item_types, $is_favorite, $enable_user_data, $image_type_limit, $enable_image_types, $user_id, $name_starts_with_or_greater, $name_starts_with, $name_less_than, $enable_images, $enable_total_record_count, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getStudios'
     *
     * @param  int $start_index Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)
     * @param  int $limit Optional. The maximum number of records to return. (optional)
     * @param  string $search_term Optional. Search term. (optional)
     * @param  string $parent_id Specify this to localize the search to a specific item or folder. Omit to use the root. (optional)
     * @param  \OpenAPI\Client\Model\ItemFields[] $fields Optional. Specify additional fields of information to return in the output. (optional)
     * @param  \OpenAPI\Client\Model\BaseItemKind[] $exclude_item_types Optional. If specified, results will be filtered out based on item type. This allows multiple, comma delimited. (optional)
     * @param  \OpenAPI\Client\Model\BaseItemKind[] $include_item_types Optional. If specified, results will be filtered based on item type. This allows multiple, comma delimited. (optional)
     * @param  bool $is_favorite Optional filter by items that are marked as favorite, or not. (optional)
     * @param  bool $enable_user_data Optional, include user data. (optional)
     * @param  int $image_type_limit Optional, the max number of images to return, per image type. (optional)
     * @param  \OpenAPI\Client\Model\ImageType[] $enable_image_types Optional. The image types to include in the output. (optional)
     * @param  string $user_id User id. (optional)
     * @param  string $name_starts_with_or_greater Optional filter by items whose name is sorted equally or greater than a given input string. (optional)
     * @param  string $name_starts_with Optional filter by items whose name is sorted equally than a given input string. (optional)
     * @param  string $name_less_than Optional filter by items whose name is equally or lesser than a given input string. (optional)
     * @param  bool $enable_images Optional, include image information in output. (optional, default to true)
     * @param  bool $enable_total_record_count Total record count. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStudios'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getStudiosRequest($start_index = null, $limit = null, $search_term = null, $parent_id = null, $fields = null, $exclude_item_types = null, $include_item_types = null, $is_favorite = null, $enable_user_data = null, $image_type_limit = null, $enable_image_types = null, $user_id = null, $name_starts_with_or_greater = null, $name_starts_with = null, $name_less_than = null, $enable_images = true, $enable_total_record_count = true, string $contentType = self::contentTypes['getStudios'][0])
    {



















        $resourcePath = '/Studios';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_index,
            'startIndex', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search_term,
            'searchTerm', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $parent_id,
            'parentId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $exclude_item_types,
            'excludeItemTypes', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_item_types,
            'includeItemTypes', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $is_favorite,
            'isFavorite', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $enable_user_data,
            'enableUserData', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $image_type_limit,
            'imageTypeLimit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $enable_image_types,
            'enableImageTypes', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $user_id,
            'userId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $name_starts_with_or_greater,
            'nameStartsWithOrGreater', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $name_starts_with,
            'nameStartsWith', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $name_less_than,
            'nameLessThan', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $enable_images,
            'enableImages', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $enable_total_record_count,
            'enableTotalRecordCount', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/json; profile="CamelCase"', 'application/json; profile="PascalCase"', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
