<?php
/**
 * UniversalAudioApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.10
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * UniversalAudioApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UniversalAudioApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getUniversalAudioStream' => [
            'application/json',
        ],
        'headUniversalAudioStream' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getUniversalAudioStream
     *
     * Gets an audio stream.
     *
     * @param  string $item_id The item id. (required)
     * @param  string[] $container Optional. The audio container. (optional)
     * @param  string $media_source_id The media version id, if playing an alternate version. (optional)
     * @param  string $device_id The device id of the client requesting. Used to stop encoding processes when needed. (optional)
     * @param  string $user_id Optional. The user id. (optional)
     * @param  string $audio_codec Optional. The audio codec to transcode to. (optional)
     * @param  int $max_audio_channels Optional. The maximum number of audio channels. (optional)
     * @param  int $transcoding_audio_channels Optional. The number of how many audio channels to transcode to. (optional)
     * @param  int $max_streaming_bitrate Optional. The maximum streaming bitrate. (optional)
     * @param  int $audio_bit_rate Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults. (optional)
     * @param  int $start_time_ticks Optional. Specify a starting offset, in ticks. 1 tick &#x3D; 10000 ms. (optional)
     * @param  string $transcoding_container Optional. The container to transcode to. (optional)
     * @param  string $transcoding_protocol Optional. The transcoding protocol. (optional)
     * @param  int $max_audio_sample_rate Optional. The maximum audio sample rate. (optional)
     * @param  int $max_audio_bit_depth Optional. The maximum audio bit depth. (optional)
     * @param  bool $enable_remote_media Optional. Whether to enable remote media. (optional)
     * @param  bool $break_on_non_key_frames Optional. Whether to break on non key frames. (optional, default to false)
     * @param  bool $enable_redirection Whether to enable redirection. Defaults to true. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUniversalAudioStream'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SplFileObject
     */
    public function getUniversalAudioStream($item_id, $container = null, $media_source_id = null, $device_id = null, $user_id = null, $audio_codec = null, $max_audio_channels = null, $transcoding_audio_channels = null, $max_streaming_bitrate = null, $audio_bit_rate = null, $start_time_ticks = null, $transcoding_container = null, $transcoding_protocol = null, $max_audio_sample_rate = null, $max_audio_bit_depth = null, $enable_remote_media = null, $break_on_non_key_frames = false, $enable_redirection = true, string $contentType = self::contentTypes['getUniversalAudioStream'][0])
    {
        list($response) = $this->getUniversalAudioStreamWithHttpInfo($item_id, $container, $media_source_id, $device_id, $user_id, $audio_codec, $max_audio_channels, $transcoding_audio_channels, $max_streaming_bitrate, $audio_bit_rate, $start_time_ticks, $transcoding_container, $transcoding_protocol, $max_audio_sample_rate, $max_audio_bit_depth, $enable_remote_media, $break_on_non_key_frames, $enable_redirection, $contentType);
        return $response;
    }

    /**
     * Operation getUniversalAudioStreamWithHttpInfo
     *
     * Gets an audio stream.
     *
     * @param  string $item_id The item id. (required)
     * @param  string[] $container Optional. The audio container. (optional)
     * @param  string $media_source_id The media version id, if playing an alternate version. (optional)
     * @param  string $device_id The device id of the client requesting. Used to stop encoding processes when needed. (optional)
     * @param  string $user_id Optional. The user id. (optional)
     * @param  string $audio_codec Optional. The audio codec to transcode to. (optional)
     * @param  int $max_audio_channels Optional. The maximum number of audio channels. (optional)
     * @param  int $transcoding_audio_channels Optional. The number of how many audio channels to transcode to. (optional)
     * @param  int $max_streaming_bitrate Optional. The maximum streaming bitrate. (optional)
     * @param  int $audio_bit_rate Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults. (optional)
     * @param  int $start_time_ticks Optional. Specify a starting offset, in ticks. 1 tick &#x3D; 10000 ms. (optional)
     * @param  string $transcoding_container Optional. The container to transcode to. (optional)
     * @param  string $transcoding_protocol Optional. The transcoding protocol. (optional)
     * @param  int $max_audio_sample_rate Optional. The maximum audio sample rate. (optional)
     * @param  int $max_audio_bit_depth Optional. The maximum audio bit depth. (optional)
     * @param  bool $enable_remote_media Optional. Whether to enable remote media. (optional)
     * @param  bool $break_on_non_key_frames Optional. Whether to break on non key frames. (optional, default to false)
     * @param  bool $enable_redirection Whether to enable redirection. Defaults to true. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUniversalAudioStream'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUniversalAudioStreamWithHttpInfo($item_id, $container = null, $media_source_id = null, $device_id = null, $user_id = null, $audio_codec = null, $max_audio_channels = null, $transcoding_audio_channels = null, $max_streaming_bitrate = null, $audio_bit_rate = null, $start_time_ticks = null, $transcoding_container = null, $transcoding_protocol = null, $max_audio_sample_rate = null, $max_audio_bit_depth = null, $enable_remote_media = null, $break_on_non_key_frames = false, $enable_redirection = true, string $contentType = self::contentTypes['getUniversalAudioStream'][0])
    {
        $request = $this->getUniversalAudioStreamRequest($item_id, $container, $media_source_id, $device_id, $user_id, $audio_codec, $max_audio_channels, $transcoding_audio_channels, $max_streaming_bitrate, $audio_bit_rate, $start_time_ticks, $transcoding_container, $transcoding_protocol, $max_audio_sample_rate, $max_audio_bit_depth, $enable_remote_media, $break_on_non_key_frames, $enable_redirection, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\SplFileObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SplFileObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SplFileObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SplFileObject';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SplFileObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getUniversalAudioStreamAsync
     *
     * Gets an audio stream.
     *
     * @param  string $item_id The item id. (required)
     * @param  string[] $container Optional. The audio container. (optional)
     * @param  string $media_source_id The media version id, if playing an alternate version. (optional)
     * @param  string $device_id The device id of the client requesting. Used to stop encoding processes when needed. (optional)
     * @param  string $user_id Optional. The user id. (optional)
     * @param  string $audio_codec Optional. The audio codec to transcode to. (optional)
     * @param  int $max_audio_channels Optional. The maximum number of audio channels. (optional)
     * @param  int $transcoding_audio_channels Optional. The number of how many audio channels to transcode to. (optional)
     * @param  int $max_streaming_bitrate Optional. The maximum streaming bitrate. (optional)
     * @param  int $audio_bit_rate Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults. (optional)
     * @param  int $start_time_ticks Optional. Specify a starting offset, in ticks. 1 tick &#x3D; 10000 ms. (optional)
     * @param  string $transcoding_container Optional. The container to transcode to. (optional)
     * @param  string $transcoding_protocol Optional. The transcoding protocol. (optional)
     * @param  int $max_audio_sample_rate Optional. The maximum audio sample rate. (optional)
     * @param  int $max_audio_bit_depth Optional. The maximum audio bit depth. (optional)
     * @param  bool $enable_remote_media Optional. Whether to enable remote media. (optional)
     * @param  bool $break_on_non_key_frames Optional. Whether to break on non key frames. (optional, default to false)
     * @param  bool $enable_redirection Whether to enable redirection. Defaults to true. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUniversalAudioStream'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUniversalAudioStreamAsync($item_id, $container = null, $media_source_id = null, $device_id = null, $user_id = null, $audio_codec = null, $max_audio_channels = null, $transcoding_audio_channels = null, $max_streaming_bitrate = null, $audio_bit_rate = null, $start_time_ticks = null, $transcoding_container = null, $transcoding_protocol = null, $max_audio_sample_rate = null, $max_audio_bit_depth = null, $enable_remote_media = null, $break_on_non_key_frames = false, $enable_redirection = true, string $contentType = self::contentTypes['getUniversalAudioStream'][0])
    {
        return $this->getUniversalAudioStreamAsyncWithHttpInfo($item_id, $container, $media_source_id, $device_id, $user_id, $audio_codec, $max_audio_channels, $transcoding_audio_channels, $max_streaming_bitrate, $audio_bit_rate, $start_time_ticks, $transcoding_container, $transcoding_protocol, $max_audio_sample_rate, $max_audio_bit_depth, $enable_remote_media, $break_on_non_key_frames, $enable_redirection, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUniversalAudioStreamAsyncWithHttpInfo
     *
     * Gets an audio stream.
     *
     * @param  string $item_id The item id. (required)
     * @param  string[] $container Optional. The audio container. (optional)
     * @param  string $media_source_id The media version id, if playing an alternate version. (optional)
     * @param  string $device_id The device id of the client requesting. Used to stop encoding processes when needed. (optional)
     * @param  string $user_id Optional. The user id. (optional)
     * @param  string $audio_codec Optional. The audio codec to transcode to. (optional)
     * @param  int $max_audio_channels Optional. The maximum number of audio channels. (optional)
     * @param  int $transcoding_audio_channels Optional. The number of how many audio channels to transcode to. (optional)
     * @param  int $max_streaming_bitrate Optional. The maximum streaming bitrate. (optional)
     * @param  int $audio_bit_rate Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults. (optional)
     * @param  int $start_time_ticks Optional. Specify a starting offset, in ticks. 1 tick &#x3D; 10000 ms. (optional)
     * @param  string $transcoding_container Optional. The container to transcode to. (optional)
     * @param  string $transcoding_protocol Optional. The transcoding protocol. (optional)
     * @param  int $max_audio_sample_rate Optional. The maximum audio sample rate. (optional)
     * @param  int $max_audio_bit_depth Optional. The maximum audio bit depth. (optional)
     * @param  bool $enable_remote_media Optional. Whether to enable remote media. (optional)
     * @param  bool $break_on_non_key_frames Optional. Whether to break on non key frames. (optional, default to false)
     * @param  bool $enable_redirection Whether to enable redirection. Defaults to true. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUniversalAudioStream'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUniversalAudioStreamAsyncWithHttpInfo($item_id, $container = null, $media_source_id = null, $device_id = null, $user_id = null, $audio_codec = null, $max_audio_channels = null, $transcoding_audio_channels = null, $max_streaming_bitrate = null, $audio_bit_rate = null, $start_time_ticks = null, $transcoding_container = null, $transcoding_protocol = null, $max_audio_sample_rate = null, $max_audio_bit_depth = null, $enable_remote_media = null, $break_on_non_key_frames = false, $enable_redirection = true, string $contentType = self::contentTypes['getUniversalAudioStream'][0])
    {
        $returnType = '\SplFileObject';
        $request = $this->getUniversalAudioStreamRequest($item_id, $container, $media_source_id, $device_id, $user_id, $audio_codec, $max_audio_channels, $transcoding_audio_channels, $max_streaming_bitrate, $audio_bit_rate, $start_time_ticks, $transcoding_container, $transcoding_protocol, $max_audio_sample_rate, $max_audio_bit_depth, $enable_remote_media, $break_on_non_key_frames, $enable_redirection, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUniversalAudioStream'
     *
     * @param  string $item_id The item id. (required)
     * @param  string[] $container Optional. The audio container. (optional)
     * @param  string $media_source_id The media version id, if playing an alternate version. (optional)
     * @param  string $device_id The device id of the client requesting. Used to stop encoding processes when needed. (optional)
     * @param  string $user_id Optional. The user id. (optional)
     * @param  string $audio_codec Optional. The audio codec to transcode to. (optional)
     * @param  int $max_audio_channels Optional. The maximum number of audio channels. (optional)
     * @param  int $transcoding_audio_channels Optional. The number of how many audio channels to transcode to. (optional)
     * @param  int $max_streaming_bitrate Optional. The maximum streaming bitrate. (optional)
     * @param  int $audio_bit_rate Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults. (optional)
     * @param  int $start_time_ticks Optional. Specify a starting offset, in ticks. 1 tick &#x3D; 10000 ms. (optional)
     * @param  string $transcoding_container Optional. The container to transcode to. (optional)
     * @param  string $transcoding_protocol Optional. The transcoding protocol. (optional)
     * @param  int $max_audio_sample_rate Optional. The maximum audio sample rate. (optional)
     * @param  int $max_audio_bit_depth Optional. The maximum audio bit depth. (optional)
     * @param  bool $enable_remote_media Optional. Whether to enable remote media. (optional)
     * @param  bool $break_on_non_key_frames Optional. Whether to break on non key frames. (optional, default to false)
     * @param  bool $enable_redirection Whether to enable redirection. Defaults to true. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUniversalAudioStream'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getUniversalAudioStreamRequest($item_id, $container = null, $media_source_id = null, $device_id = null, $user_id = null, $audio_codec = null, $max_audio_channels = null, $transcoding_audio_channels = null, $max_streaming_bitrate = null, $audio_bit_rate = null, $start_time_ticks = null, $transcoding_container = null, $transcoding_protocol = null, $max_audio_sample_rate = null, $max_audio_bit_depth = null, $enable_remote_media = null, $break_on_non_key_frames = false, $enable_redirection = true, string $contentType = self::contentTypes['getUniversalAudioStream'][0])
    {

        // verify the required parameter 'item_id' is set
        if ($item_id === null || (is_array($item_id) && count($item_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $item_id when calling getUniversalAudioStream'
            );
        }



















        $resourcePath = '/Audio/{itemId}/universal';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $container,
            'container', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $media_source_id,
            'mediaSourceId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $device_id,
            'deviceId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $user_id,
            'userId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $audio_codec,
            'audioCodec', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $max_audio_channels,
            'maxAudioChannels', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $transcoding_audio_channels,
            'transcodingAudioChannels', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $max_streaming_bitrate,
            'maxStreamingBitrate', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $audio_bit_rate,
            'audioBitRate', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_time_ticks,
            'startTimeTicks', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $transcoding_container,
            'transcodingContainer', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $transcoding_protocol,
            'transcodingProtocol', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $max_audio_sample_rate,
            'maxAudioSampleRate', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $max_audio_bit_depth,
            'maxAudioBitDepth', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $enable_remote_media,
            'enableRemoteMedia', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $break_on_non_key_frames,
            'breakOnNonKeyFrames', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $enable_redirection,
            'enableRedirection', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($item_id !== null) {
            $resourcePath = str_replace(
                '{' . 'itemId' . '}',
                ObjectSerializer::toPathValue($item_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['audio/*', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Emby-Token');
        if ($apiKey !== null) {
            $headers['X-Emby-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation headUniversalAudioStream
     *
     * Gets an audio stream.
     *
     * @param  string $item_id The item id. (required)
     * @param  string[] $container Optional. The audio container. (optional)
     * @param  string $media_source_id The media version id, if playing an alternate version. (optional)
     * @param  string $device_id The device id of the client requesting. Used to stop encoding processes when needed. (optional)
     * @param  string $user_id Optional. The user id. (optional)
     * @param  string $audio_codec Optional. The audio codec to transcode to. (optional)
     * @param  int $max_audio_channels Optional. The maximum number of audio channels. (optional)
     * @param  int $transcoding_audio_channels Optional. The number of how many audio channels to transcode to. (optional)
     * @param  int $max_streaming_bitrate Optional. The maximum streaming bitrate. (optional)
     * @param  int $audio_bit_rate Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults. (optional)
     * @param  int $start_time_ticks Optional. Specify a starting offset, in ticks. 1 tick &#x3D; 10000 ms. (optional)
     * @param  string $transcoding_container Optional. The container to transcode to. (optional)
     * @param  string $transcoding_protocol Optional. The transcoding protocol. (optional)
     * @param  int $max_audio_sample_rate Optional. The maximum audio sample rate. (optional)
     * @param  int $max_audio_bit_depth Optional. The maximum audio bit depth. (optional)
     * @param  bool $enable_remote_media Optional. Whether to enable remote media. (optional)
     * @param  bool $break_on_non_key_frames Optional. Whether to break on non key frames. (optional, default to false)
     * @param  bool $enable_redirection Whether to enable redirection. Defaults to true. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['headUniversalAudioStream'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SplFileObject
     */
    public function headUniversalAudioStream($item_id, $container = null, $media_source_id = null, $device_id = null, $user_id = null, $audio_codec = null, $max_audio_channels = null, $transcoding_audio_channels = null, $max_streaming_bitrate = null, $audio_bit_rate = null, $start_time_ticks = null, $transcoding_container = null, $transcoding_protocol = null, $max_audio_sample_rate = null, $max_audio_bit_depth = null, $enable_remote_media = null, $break_on_non_key_frames = false, $enable_redirection = true, string $contentType = self::contentTypes['headUniversalAudioStream'][0])
    {
        list($response) = $this->headUniversalAudioStreamWithHttpInfo($item_id, $container, $media_source_id, $device_id, $user_id, $audio_codec, $max_audio_channels, $transcoding_audio_channels, $max_streaming_bitrate, $audio_bit_rate, $start_time_ticks, $transcoding_container, $transcoding_protocol, $max_audio_sample_rate, $max_audio_bit_depth, $enable_remote_media, $break_on_non_key_frames, $enable_redirection, $contentType);
        return $response;
    }

    /**
     * Operation headUniversalAudioStreamWithHttpInfo
     *
     * Gets an audio stream.
     *
     * @param  string $item_id The item id. (required)
     * @param  string[] $container Optional. The audio container. (optional)
     * @param  string $media_source_id The media version id, if playing an alternate version. (optional)
     * @param  string $device_id The device id of the client requesting. Used to stop encoding processes when needed. (optional)
     * @param  string $user_id Optional. The user id. (optional)
     * @param  string $audio_codec Optional. The audio codec to transcode to. (optional)
     * @param  int $max_audio_channels Optional. The maximum number of audio channels. (optional)
     * @param  int $transcoding_audio_channels Optional. The number of how many audio channels to transcode to. (optional)
     * @param  int $max_streaming_bitrate Optional. The maximum streaming bitrate. (optional)
     * @param  int $audio_bit_rate Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults. (optional)
     * @param  int $start_time_ticks Optional. Specify a starting offset, in ticks. 1 tick &#x3D; 10000 ms. (optional)
     * @param  string $transcoding_container Optional. The container to transcode to. (optional)
     * @param  string $transcoding_protocol Optional. The transcoding protocol. (optional)
     * @param  int $max_audio_sample_rate Optional. The maximum audio sample rate. (optional)
     * @param  int $max_audio_bit_depth Optional. The maximum audio bit depth. (optional)
     * @param  bool $enable_remote_media Optional. Whether to enable remote media. (optional)
     * @param  bool $break_on_non_key_frames Optional. Whether to break on non key frames. (optional, default to false)
     * @param  bool $enable_redirection Whether to enable redirection. Defaults to true. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['headUniversalAudioStream'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function headUniversalAudioStreamWithHttpInfo($item_id, $container = null, $media_source_id = null, $device_id = null, $user_id = null, $audio_codec = null, $max_audio_channels = null, $transcoding_audio_channels = null, $max_streaming_bitrate = null, $audio_bit_rate = null, $start_time_ticks = null, $transcoding_container = null, $transcoding_protocol = null, $max_audio_sample_rate = null, $max_audio_bit_depth = null, $enable_remote_media = null, $break_on_non_key_frames = false, $enable_redirection = true, string $contentType = self::contentTypes['headUniversalAudioStream'][0])
    {
        $request = $this->headUniversalAudioStreamRequest($item_id, $container, $media_source_id, $device_id, $user_id, $audio_codec, $max_audio_channels, $transcoding_audio_channels, $max_streaming_bitrate, $audio_bit_rate, $start_time_ticks, $transcoding_container, $transcoding_protocol, $max_audio_sample_rate, $max_audio_bit_depth, $enable_remote_media, $break_on_non_key_frames, $enable_redirection, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\SplFileObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SplFileObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SplFileObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SplFileObject';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SplFileObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation headUniversalAudioStreamAsync
     *
     * Gets an audio stream.
     *
     * @param  string $item_id The item id. (required)
     * @param  string[] $container Optional. The audio container. (optional)
     * @param  string $media_source_id The media version id, if playing an alternate version. (optional)
     * @param  string $device_id The device id of the client requesting. Used to stop encoding processes when needed. (optional)
     * @param  string $user_id Optional. The user id. (optional)
     * @param  string $audio_codec Optional. The audio codec to transcode to. (optional)
     * @param  int $max_audio_channels Optional. The maximum number of audio channels. (optional)
     * @param  int $transcoding_audio_channels Optional. The number of how many audio channels to transcode to. (optional)
     * @param  int $max_streaming_bitrate Optional. The maximum streaming bitrate. (optional)
     * @param  int $audio_bit_rate Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults. (optional)
     * @param  int $start_time_ticks Optional. Specify a starting offset, in ticks. 1 tick &#x3D; 10000 ms. (optional)
     * @param  string $transcoding_container Optional. The container to transcode to. (optional)
     * @param  string $transcoding_protocol Optional. The transcoding protocol. (optional)
     * @param  int $max_audio_sample_rate Optional. The maximum audio sample rate. (optional)
     * @param  int $max_audio_bit_depth Optional. The maximum audio bit depth. (optional)
     * @param  bool $enable_remote_media Optional. Whether to enable remote media. (optional)
     * @param  bool $break_on_non_key_frames Optional. Whether to break on non key frames. (optional, default to false)
     * @param  bool $enable_redirection Whether to enable redirection. Defaults to true. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['headUniversalAudioStream'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function headUniversalAudioStreamAsync($item_id, $container = null, $media_source_id = null, $device_id = null, $user_id = null, $audio_codec = null, $max_audio_channels = null, $transcoding_audio_channels = null, $max_streaming_bitrate = null, $audio_bit_rate = null, $start_time_ticks = null, $transcoding_container = null, $transcoding_protocol = null, $max_audio_sample_rate = null, $max_audio_bit_depth = null, $enable_remote_media = null, $break_on_non_key_frames = false, $enable_redirection = true, string $contentType = self::contentTypes['headUniversalAudioStream'][0])
    {
        return $this->headUniversalAudioStreamAsyncWithHttpInfo($item_id, $container, $media_source_id, $device_id, $user_id, $audio_codec, $max_audio_channels, $transcoding_audio_channels, $max_streaming_bitrate, $audio_bit_rate, $start_time_ticks, $transcoding_container, $transcoding_protocol, $max_audio_sample_rate, $max_audio_bit_depth, $enable_remote_media, $break_on_non_key_frames, $enable_redirection, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation headUniversalAudioStreamAsyncWithHttpInfo
     *
     * Gets an audio stream.
     *
     * @param  string $item_id The item id. (required)
     * @param  string[] $container Optional. The audio container. (optional)
     * @param  string $media_source_id The media version id, if playing an alternate version. (optional)
     * @param  string $device_id The device id of the client requesting. Used to stop encoding processes when needed. (optional)
     * @param  string $user_id Optional. The user id. (optional)
     * @param  string $audio_codec Optional. The audio codec to transcode to. (optional)
     * @param  int $max_audio_channels Optional. The maximum number of audio channels. (optional)
     * @param  int $transcoding_audio_channels Optional. The number of how many audio channels to transcode to. (optional)
     * @param  int $max_streaming_bitrate Optional. The maximum streaming bitrate. (optional)
     * @param  int $audio_bit_rate Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults. (optional)
     * @param  int $start_time_ticks Optional. Specify a starting offset, in ticks. 1 tick &#x3D; 10000 ms. (optional)
     * @param  string $transcoding_container Optional. The container to transcode to. (optional)
     * @param  string $transcoding_protocol Optional. The transcoding protocol. (optional)
     * @param  int $max_audio_sample_rate Optional. The maximum audio sample rate. (optional)
     * @param  int $max_audio_bit_depth Optional. The maximum audio bit depth. (optional)
     * @param  bool $enable_remote_media Optional. Whether to enable remote media. (optional)
     * @param  bool $break_on_non_key_frames Optional. Whether to break on non key frames. (optional, default to false)
     * @param  bool $enable_redirection Whether to enable redirection. Defaults to true. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['headUniversalAudioStream'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function headUniversalAudioStreamAsyncWithHttpInfo($item_id, $container = null, $media_source_id = null, $device_id = null, $user_id = null, $audio_codec = null, $max_audio_channels = null, $transcoding_audio_channels = null, $max_streaming_bitrate = null, $audio_bit_rate = null, $start_time_ticks = null, $transcoding_container = null, $transcoding_protocol = null, $max_audio_sample_rate = null, $max_audio_bit_depth = null, $enable_remote_media = null, $break_on_non_key_frames = false, $enable_redirection = true, string $contentType = self::contentTypes['headUniversalAudioStream'][0])
    {
        $returnType = '\SplFileObject';
        $request = $this->headUniversalAudioStreamRequest($item_id, $container, $media_source_id, $device_id, $user_id, $audio_codec, $max_audio_channels, $transcoding_audio_channels, $max_streaming_bitrate, $audio_bit_rate, $start_time_ticks, $transcoding_container, $transcoding_protocol, $max_audio_sample_rate, $max_audio_bit_depth, $enable_remote_media, $break_on_non_key_frames, $enable_redirection, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'headUniversalAudioStream'
     *
     * @param  string $item_id The item id. (required)
     * @param  string[] $container Optional. The audio container. (optional)
     * @param  string $media_source_id The media version id, if playing an alternate version. (optional)
     * @param  string $device_id The device id of the client requesting. Used to stop encoding processes when needed. (optional)
     * @param  string $user_id Optional. The user id. (optional)
     * @param  string $audio_codec Optional. The audio codec to transcode to. (optional)
     * @param  int $max_audio_channels Optional. The maximum number of audio channels. (optional)
     * @param  int $transcoding_audio_channels Optional. The number of how many audio channels to transcode to. (optional)
     * @param  int $max_streaming_bitrate Optional. The maximum streaming bitrate. (optional)
     * @param  int $audio_bit_rate Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults. (optional)
     * @param  int $start_time_ticks Optional. Specify a starting offset, in ticks. 1 tick &#x3D; 10000 ms. (optional)
     * @param  string $transcoding_container Optional. The container to transcode to. (optional)
     * @param  string $transcoding_protocol Optional. The transcoding protocol. (optional)
     * @param  int $max_audio_sample_rate Optional. The maximum audio sample rate. (optional)
     * @param  int $max_audio_bit_depth Optional. The maximum audio bit depth. (optional)
     * @param  bool $enable_remote_media Optional. Whether to enable remote media. (optional)
     * @param  bool $break_on_non_key_frames Optional. Whether to break on non key frames. (optional, default to false)
     * @param  bool $enable_redirection Whether to enable redirection. Defaults to true. (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['headUniversalAudioStream'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function headUniversalAudioStreamRequest($item_id, $container = null, $media_source_id = null, $device_id = null, $user_id = null, $audio_codec = null, $max_audio_channels = null, $transcoding_audio_channels = null, $max_streaming_bitrate = null, $audio_bit_rate = null, $start_time_ticks = null, $transcoding_container = null, $transcoding_protocol = null, $max_audio_sample_rate = null, $max_audio_bit_depth = null, $enable_remote_media = null, $break_on_non_key_frames = false, $enable_redirection = true, string $contentType = self::contentTypes['headUniversalAudioStream'][0])
    {

        // verify the required parameter 'item_id' is set
        if ($item_id === null || (is_array($item_id) && count($item_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $item_id when calling headUniversalAudioStream'
            );
        }



















        $resourcePath = '/Audio/{itemId}/universal';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $container,
            'container', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $media_source_id,
            'mediaSourceId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $device_id,
            'deviceId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $user_id,
            'userId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $audio_codec,
            'audioCodec', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $max_audio_channels,
            'maxAudioChannels', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $transcoding_audio_channels,
            'transcodingAudioChannels', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $max_streaming_bitrate,
            'maxStreamingBitrate', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $audio_bit_rate,
            'audioBitRate', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_time_ticks,
            'startTimeTicks', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $transcoding_container,
            'transcodingContainer', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $transcoding_protocol,
            'transcodingProtocol', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $max_audio_sample_rate,
            'maxAudioSampleRate', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $max_audio_bit_depth,
            'maxAudioBitDepth', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $enable_remote_media,
            'enableRemoteMedia', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $break_on_non_key_frames,
            'breakOnNonKeyFrames', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $enable_redirection,
            'enableRedirection', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($item_id !== null) {
            $resourcePath = str_replace(
                '{' . 'itemId' . '}',
                ObjectSerializer::toPathValue($item_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['audio/*', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Emby-Token');
        if ($apiKey !== null) {
            $headers['X-Emby-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'HEAD',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
