<?php
/**
 * ProfileConditionType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.10
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ProfileConditionType Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProfileConditionType
{
    /**
     * Possible values of this enum
     */
    public const EQUALS = 'Equals';

    public const NOT_EQUALS = 'NotEquals';

    public const LESS_THAN_EQUAL = 'LessThanEqual';

    public const GREATER_THAN_EQUAL = 'GreaterThanEqual';

    public const EQUALS_ANY = 'EqualsAny';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EQUALS,
            self::NOT_EQUALS,
            self::LESS_THAN_EQUAL,
            self::GREATER_THAN_EQUAL,
            self::EQUALS_ANY
        ];
    }
}


