<?php
/**
 * SubtitleDeliveryMethod
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.10
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SubtitleDeliveryMethod Class Doc Comment
 *
 * @category Class
 * @description Delivery method to use during playback of a specific subtitle format.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SubtitleDeliveryMethod
{
    /**
     * Possible values of this enum
     */
    public const ENCODE = 'Encode';

    public const EMBED = 'Embed';

    public const EXTERNAL = 'External';

    public const HLS = 'Hls';

    public const DROP = 'Drop';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ENCODE,
            self::EMBED,
            self::EXTERNAL,
            self::HLS,
            self::DROP
        ];
    }
}


